In [3]:
import numpy as np

## Write a Numpy program to compute the multiplication of two given matrixes

In [12]:
def mulMatrices(m1,m2):
  assert np.shape(m1)==np.shape(m2),'Not Same Dimensions'
  return np.dot(m1,m2)

In [17]:
matx1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matx2 = np.array([[4,4,4],[1,2,2],[0,3,9]])

print(mulMatrices(matx1,matx2))

[[  6  17  35]
 [ 21  44  80]
 [ 36  71 125]]


## Write a NumPy program to compute the determinant of a given square array

In [14]:
def detMatrices(m):
  assert np.shape(m)[0]==np.shape(m)[1],'Not Square Matrix'
  return np.linalg.det(m)

In [22]:
print(detMatrices(matx2))

24.000000000000004


## Write a NumPy program to compute the cross product of two given vectors

In [24]:
def crossProd(v1,v2):
  assert np.shape(v1)==np.shape(v2),'Not Same Dimensions'
  return np.cross(v1,v2)

In [25]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

print(crossProd(vec1,vec2))

[-3  6 -3]


## Write a NumPy program to compute the condition number of a given matrix

In [27]:
def condMatx(m):
  return np.linalg.cond(m)

In [30]:
print(condMatx(matx1))

3.813147060626918e+16


## Write a NumPy program to compute the inverse of a given matrix

In [34]:
from numpy.linalg.linalg import LinAlgError
def invMatx(m):
  try:
    return np.linalg.inv(m)
  except LinAlgError:
    print('Singular Matrix')

In [37]:
print(invMatx(matx2))

[[ 0.5        -1.          0.        ]
 [-0.375       1.5        -0.16666667]
 [ 0.125      -0.5         0.16666667]]
